name: Ghidra CSKY Extension Build

env:
  ghidra-url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.4.2_build/ghidra_11.4.2_PUBLIC_20250826.zip
  ghidra-zip-filename: ghidra_11.4.2_PUBLIC_20250826.zip
  ghidra-directory: ghidra_11.4.2_PUBLIC

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Ghidra release
      uses: carlosperate/download-file-action@v1.0.3
      id: download-ghidra
      with:
        file-url: ${{ env.ghidra-url }}
        file-name: ${{ env.ghidra-zip-filename }}

    - name: Unzip Ghidra
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ${{ steps.download-ghidra.outputs.file-path }} -d .
    - uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build extension
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: '8.5'
        build-root-directory: ${{ github.workspace }}/CSKY
        arguments: '-PGHIDRA_INSTALL_DIR=${{ github.workspace }}/${{ env.ghidra-directory }}'

    - name: Upload built extension
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: CSKY/dist/*.zip

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs: build

    steps:
    - name: Download built extension
      uses: actions/download-artifact@v4
      with:
        name: extension
    - name: Upload extension to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '*.zip'
